# AI .. ML >>> sml .. unsml .. rein ml

# sml .. class .. regress

# class -- binary .. multi class

# agarda target ustuni bitta bo'lsa -- single output -- deyiladi

# agarda target ustuni bir nechta bo'lsa -- multi output -- deyiladi

# Binary >> 2 ta sinf, target ustuni bitta 

# Multi-class >> 2 dan kop sinf, target baribir bitta ustun

# Multi - output  >> bir nechta target ustun 

# Multi-Label Classification - bir  sample bir vaqtning o'zida bir nechta labelga ega bo'lishi mumkin.

# Binary Classification

In [3]:
from sklearn.datasets import load_breast_cancer
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

data = load_breast_cancer()

x= data.data
y= data.target

x_train, x_test, y_train, y_test =  train_test_split(x,y,test_size=0.2, random_state=42)

model= LogisticRegression(max_iter=5000)
model.fit(x_train,y_train)

y_pred = model.predict(x_test)

print("Natija:", accuracy_score(y_test, y_pred))


Natija: 0.956140350877193


# Multi Class Classification

In [9]:
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

data = load_iris()

x= data.data
y= data.target

x_train, x_test, y_train, y_test =  train_test_split(x,y,test_size=0.2, random_state=42)

model= LogisticRegression(multi_class="multinomial",solver="lbfgs")
model.fit(x_train,y_train)

y_pred = model.predict(x_test)

print("Natija:", accuracy_score(y_test, y_pred))


Natija: 1.0


c:\Users\Jahongir\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\linear_model\_logistic.py:1272: FutureWarning: 'multi_class' was deprecated in version 1.5 and will be removed in 1.8. From then on, it will always use 'multinomial'. Leave it to its default value to avoid this warning.
  warnings.warn(


# Multi output Regression  -- target ustuni 2 ustun

In [12]:
from sklearn.datasets import make_regression
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestRegressor
from sklearn.multioutput import MultiOutputRegressor
from sklearn.metrics import mean_squared_error, r2_score

x,y = make_regression(n_samples=1000, n_features=10, n_targets=2, noise=0.2, random_state=42)
x_train, x_test, y_train, y_test =  train_test_split(x,y,test_size=0.2, random_state=42)

model= MultiOutputRegressor(RandomForestRegressor())
model.fit(x_train,y_train)

y_pred = model.predict(x_test)


mse = mean_squared_error(y_test, y_pred)
r2 = r2_score(y_test, y_pred) 


print("Multi Output Natijasi:", mse)
print("Multi Output Natijasi:", r2)


Multi Output Natijasi: 4528.843008439451
Multi Output Natijasi: 0.8206760074371662


# Multi Output Classification -- target ustun 2 ta

In [19]:
import numpy as np

# 2 ta target yasaymiz
y_multi = np.column_stack([
    y,
    (y ^ 1)  # ikkinchi target (misol uchun)
])

x_train, x_test, y_train, y_test = train_test_split(
    x, y_multi, test_size=0.2, random_state=42
)

model = MultiOutputClassifier(RandomForestClassifier(random_state=42))
model.fit(x_train, y_train)

y_pred = model.predict(x_test)

print("accuracy target 1:", accuracy_score(y_test[:,0], y_pred[:,0]))
print("accuracy target 2:", accuracy_score(y_test[:,1], y_pred[:,1]))


accuracy target 1: 0.92
accuracy target 2: 0.915


# Multi Label Classification 

In [20]:
import numpy as np
from sklearn.datasets import make_multilabel_classification
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.multioutput import MultiOutputClassifier
from sklearn.metrics import accuracy_score, hamming_loss

# 1️⃣ Multi-label dataset
X, Y = make_multilabel_classification(
    n_samples=1000,
    n_features=20,
    n_classes=3,      # 3 ta label
    n_labels=2,       # har sampleda o‘rtacha 2 ta label
    random_state=42
)

# Y shape: (1000, 3)
print(Y[:5])

# 2️⃣ Train-test split
X_train, X_test, y_train, y_test = train_test_split(
    X, Y, test_size=0.2, random_state=42
)

# 3️⃣ Model
model = MultiOutputClassifier(
    RandomForestClassifier(random_state=42)
)

# 4️⃣ Train
model.fit(X_train, y_train)

# 5️⃣ Predict
y_pred = model.predict(X_test)

# 6️⃣ Baholash
print("Exact match accuracy:",
      accuracy_score(y_test, y_pred))

print("Hamming loss:",
      hamming_loss(y_test, y_pred))


[[0 1 0]
 [0 0 0]
 [1 1 1]
 [1 1 0]
 [0 1 0]]
Exact match accuracy: 0.665
Hamming loss: 0.15333333333333332
